# Generated by Django 3.1.6 on 2021-02-28 22:29

from django.db import migrations, models
import django.db.models.deletion
import main_restaurant.models


class Migration(migrations.Migration):

    dependencies = [
        ('main_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25, unique=True)),
                ('photo', models.ImageField(upload_to=main_restaurant.models.Dish.get_file_name)),
                ('dish_order', models.IntegerField()),
                ('is_visible', models.BooleanField(default=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.CharField(max_length=150, unique=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_restaurant.category')),
            ],
        ),
    ]
