# Generated by Django 3.1.6 on 2021-03-04 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_restaurant', '0003_address_message_openinghours_phone_restinfo_story_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='restinfo',
            name='hours_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='main_restaurant.openinghours'),
        ),
    ]
