# Generated by Django 3.1.6 on 2021-03-04 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_restaurant', '0004_restinfo_hours_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_message',
            new_name='user_text',
        ),
        migrations.RemoveField(
            model_name='restinfo',
            name='hours_id',
        ),
    ]
