# Generated by Django 3.1.6 on 2021-03-04 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_restaurant', '0005_auto_20210304_1519'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='user_text',
            new_name='user_message',
        ),
        migrations.AddField(
            model_name='message',
            name='user_email',
            field=models.CharField(default=False, max_length=100),
        ),
    ]
