# Generated by Django 3.1.6 on 2021-03-04 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_restaurant', '0010_message_user_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='user_email',
        ),
    ]
