# Generated by Django 3.1.6 on 2021-03-12 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_restaurant', '0011_remove_message_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='user_email',
            field=models.EmailField(default='', max_length=254),
        ),
    ]
