# Generated by Django 3.1.6 on 2021-03-12 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_restaurant', '0013_auto_20210312_1734'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RestInfo',
        ),
    ]
