# Generated by Django 3.1.6 on 2021-03-13 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_restaurant', '0014_delete_restinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_restaurant.address')),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_restaurant.phone')),
            ],
        ),
    ]
